In [1]:
import torch

In [4]:
torch.cuda.set_device(1)

In [8]:
x = torch.empty(5,5)

In [10]:
x #values in the memory 

tensor([[ 1.5102e+12,  4.5560e-41, -7.6961e+10,  4.5560e-41,  1.7475e+12],
        [ 4.5560e-41, -7.7091e+10,  4.5560e-41, -7.1545e+10,  4.5560e-41],
        [-7.7091e+10,  4.5560e-41,  1.5102e+12,  4.5560e-41, -7.6961e+10],
        [ 4.5560e-41,  1.5102e+12,  4.5560e-41, -7.1545e+10,  4.5560e-41],
        [ 1.5102e+12,  4.5560e-41, -7.6961e+10,  4.5560e-41,  9.1120e+11]])

In [13]:
x= torch.zeros(5,3,dtype=torch.long)

In [14]:
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [15]:
x = torch.tensor([5.5,3])

In [16]:
x

tensor([5.5000, 3.0000])

In [19]:
x = x.new_ones(5,3)

In [20]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [21]:
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
x

tensor([[-0.2244, -0.7172,  0.6482],
        [-2.1879, -0.5787,  1.2330],
        [-0.1364,  0.9353, -2.7424],
        [-0.3353, -2.1465,  0.3341],
        [-0.8065,  0.0032,  2.1775]])

In [22]:
print(x.size())

torch.Size([5, 3])


In [26]:
y = torch.rand(5,3)
result = torch.empty(5,3)
torch.add(x, y, out = result)

tensor([[ 0.1636, -0.6904,  1.3439],
        [-1.1997, -0.5153,  1.2381],
        [ 0.8306,  1.8577, -1.9636],
        [ 0.2194, -1.8321,  1.0295],
        [-0.7144,  0.0866,  2.5898]])

In [31]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8) 

In [35]:
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [38]:
x = torch.randn(1)

In [39]:
print(x)
print(x.item())

tensor([-1.6024])
-1.602439045906067


## Converting torch-->numpy

In [41]:
a = torch.ones(5)
b = a. numpy()

In [42]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [44]:
import numpy as np

In [47]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [49]:
if torch.cuda.is_available():
    device = torch.device("cuda") #a cuda device object
    y = torch.ones_like(x,device=device) #create a tensor in GPU
    x = x.to(device)
    z = x+y
    print(z)
    print(z.to("cpu",torch.double))

tensor([-0.6024], device='cuda:1')
tensor([-0.6024], dtype=torch.float64)
